//! Cross-runtime cache key parity test.
//!
//! Reads `cache_parity_fixtures.json` (generated by
//! `scripts/check-cache-parity.py`) and asserts that the Rust
//! `sha256_hex(stable_stringify(payload))` matches the Node-computed
//! digest for every entry.
//!
//! Regenerate the fixtures whenever you add new corpus entries:
//!
//!     python3 scripts/check-cache-parity.py --write

use std::path::PathBuf;

use fcdocs_llm::cache_key::sha256_hex;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Fixture {
    name: String,
    payload: serde_json::Value,
    expected_sha256: String,
}

fn fixtures_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/cache_parity_fixtures.json")
}

#[test]
fn cache_keys_match_node_corpus() {
    let bytes = std::fs::read(fixtures_path()).expect("fixtures file present");
    let fixtures: Vec<Fixture> = serde_json::from_slice(&bytes).expect("parse fixtures");
    assert!(!fixtures.is_empty(), "corpus is empty");
    for f in &fixtures {
        let actual = sha256_hex(&f.payload);
        assert_eq!(
            actual, f.expected_sha256,
            "Rust cache key for '{name}' differs from Node:\n  rust: {actual}\n  node: {expected}",
            name = f.name,
            expected = f.expected_sha256
        );
    }
}
